paths:
  train: 'https://huggingface.co/datasets/Rodrigo2204/store-sales-forecast/resolve/main/train.csv'
  test: 'https://huggingface.co/datasets/Rodrigo2204/store-sales-forecast/resolve/main/test.csv'
  train_data: 'https://huggingface.co/datasets/Rodrigo2204/store-sales-forecast/resolve/main/variables/train_data.pkl'
  scaler: 'data/variables/scaler.pkl'

variables:
  categorical:
    static: ['family', 'store_nbr']
    dynamic: []
  target: 'sales'

transformations:
  normalize: True
  date_columns: True

timesteps: 5